--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6 (Homebrew)
-- Dumped by pg_dump version 17.6 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: bullets; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA bullets;


--
-- Name: entities; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA entities;


--
-- Name: news; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA news;


--
-- Name: SCHEMA news; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA news IS 'all news';


--
-- Name: sources; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA sources;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bullets; Type: TABLE; Schema: bullets; Owner: -
--

CREATE TABLE bullets.bullets (
    id bigint NOT NULL,
    bullet text NOT NULL
);


--
-- Name: bullets_id_seq; Type: SEQUENCE; Schema: bullets; Owner: -
--

ALTER TABLE bullets.bullets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bullets.bullets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: draft_bullets; Type: TABLE; Schema: bullets; Owner: -
--

CREATE TABLE bullets.draft_bullets (
    id bigint NOT NULL,
    draft_id bigint NOT NULL,
    bullet_id bigint NOT NULL
);


--
-- Name: draft_bullets_id_seq; Type: SEQUENCE; Schema: bullets; Owner: -
--

ALTER TABLE bullets.draft_bullets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bullets.draft_bullets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entities; Type: TABLE; Schema: entities; Owner: -
--

CREATE TABLE entities.entities (
    id bigint NOT NULL,
    entity text NOT NULL
);


--
-- Name: entities_id_seq; Type: SEQUENCE; Schema: entities; Owner: -
--

ALTER TABLE entities.entities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME entities.entities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_entities; Type: TABLE; Schema: entities; Owner: -
--

CREATE TABLE entities.news_entities (
    id bigint NOT NULL,
    news_id bigint NOT NULL,
    entity_id bigint NOT NULL
);


--
-- Name: news_entities_id_seq; Type: SEQUENCE; Schema: entities; Owner: -
--

ALTER TABLE entities.news_entities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME entities.news_entities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dedup_groups; Type: TABLE; Schema: news; Owner: -
--

CREATE TABLE news.dedup_groups (
    id bigint NOT NULL,
    dedup_group text NOT NULL
);


--
-- Name: dedup_groups_id_seq; Type: SEQUENCE; Schema: news; Owner: -
--

ALTER TABLE news.dedup_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME news.dedup_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: draft; Type: TABLE; Schema: news; Owner: -
--

CREATE TABLE news.draft (
    id bigint NOT NULL,
    title text NOT NULL,
    lead text,
    quote text
);


--
-- Name: draft_id_seq; Type: SEQUENCE; Schema: news; Owner: -
--

ALTER TABLE news.draft ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME news.draft_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news; Type: TABLE; Schema: news; Owner: -
--

CREATE TABLE news.news (
    id bigint NOT NULL,
    headline text NOT NULL,
    hotness numeric NOT NULL,
    why_now text,
    timeline timestamp with time zone NOT NULL,
    draft_id bigint,
    dedup_group_id bigint
);


--
-- Name: TABLE news; Type: COMMENT; Schema: news; Owner: -
--

COMMENT ON TABLE news.news IS 'main news table';


--
-- Name: news_id_seq; Type: SEQUENCE; Schema: news; Owner: -
--

ALTER TABLE news.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME news.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_sources; Type: TABLE; Schema: sources; Owner: -
--

CREATE TABLE sources.news_sources (
    news_id bigint NOT NULL,
    id bigint NOT NULL,
    source_id bigint NOT NULL
);


--
-- Name: news_sources_id_seq; Type: SEQUENCE; Schema: sources; Owner: -
--

ALTER TABLE sources.news_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sources.news_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sources; Type: TABLE; Schema: sources; Owner: -
--

CREATE TABLE sources.sources (
    id bigint NOT NULL,
    source text NOT NULL
);


--
-- Name: sources_id_seq; Type: SEQUENCE; Schema: sources; Owner: -
--

ALTER TABLE sources.sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sources.sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bullets bullets_bullet_key; Type: CONSTRAINT; Schema: bullets; Owner: -
--

ALTER TABLE ONLY bullets.bullets
    ADD CONSTRAINT bullets_bullet_key UNIQUE (bullet);


--
-- Name: bullets bullets_pkey; Type: CONSTRAINT; Schema: bullets; Owner: -
--

ALTER TABLE ONLY bullets.bullets
    ADD CONSTRAINT bullets_pkey PRIMARY KEY (id);


--
-- Name: draft_bullets draft_bullets_pk; Type: CONSTRAINT; Schema: bullets; Owner: -
--

ALTER TABLE ONLY bullets.draft_bullets
    ADD CONSTRAINT draft_bullets_pk UNIQUE (draft_id, bullet_id);


--
-- Name: draft_bullets draft_bullets_pkey; Type: CONSTRAINT; Schema: bullets; Owner: -
--

ALTER TABLE ONLY bullets.draft_bullets
    ADD CONSTRAINT draft_bullets_pkey PRIMARY KEY (id);


--
-- Name: entities entities_entity_key; Type: CONSTRAINT; Schema: entities; Owner: -
--

ALTER TABLE ONLY entities.entities
    ADD CONSTRAINT entities_entity_key UNIQUE (entity);


--
-- Name: entities entities_pkey; Type: CONSTRAINT; Schema: entities; Owner: -
--

ALTER TABLE ONLY entities.entities
    ADD CONSTRAINT entities_pkey PRIMARY KEY (id);


--
-- Name: news_entities news_entities_pk; Type: CONSTRAINT; Schema: entities; Owner: -
--

ALTER TABLE ONLY entities.news_entities
    ADD CONSTRAINT news_entities_pk UNIQUE (news_id, entity_id);


--
-- Name: news_entities news_entities_pkey; Type: CONSTRAINT; Schema: entities; Owner: -
--

ALTER TABLE ONLY entities.news_entities
    ADD CONSTRAINT news_entities_pkey PRIMARY KEY (id);


--
-- Name: dedup_groups dedup_groups_dedup_group_key; Type: CONSTRAINT; Schema: news; Owner: -
--

ALTER TABLE ONLY news.dedup_groups
    ADD CONSTRAINT dedup_groups_dedup_group_key UNIQUE (dedup_group);


--
-- Name: dedup_groups dedup_groups_pkey; Type: CONSTRAINT; Schema: news; Owner: -
--

ALTER TABLE ONLY news.dedup_groups
    ADD CONSTRAINT dedup_groups_pkey PRIMARY KEY (id);


--
-- Name: draft draft_pkey; Type: CONSTRAINT; Schema: news; Owner: -
--

ALTER TABLE ONLY news.draft
    ADD CONSTRAINT draft_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: news; Owner: -
--

ALTER TABLE ONLY news.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: news_sources news_sources_pk; Type: CONSTRAINT; Schema: sources; Owner: -
--

ALTER TABLE ONLY sources.news_sources
    ADD CONSTRAINT news_sources_pk UNIQUE (news_id, source_id);


--
-- Name: news_sources news_sources_pkey; Type: CONSTRAINT; Schema: sources; Owner: -
--

ALTER TABLE ONLY sources.news_sources
    ADD CONSTRAINT news_sources_pkey PRIMARY KEY (id);


--
-- Name: sources sources_pkey; Type: CONSTRAINT; Schema: sources; Owner: -
--

ALTER TABLE ONLY sources.sources
    ADD CONSTRAINT sources_pkey PRIMARY KEY (id);


--
-- Name: sources sources_source_key; Type: CONSTRAINT; Schema: sources; Owner: -
--

ALTER TABLE ONLY sources.sources
    ADD CONSTRAINT sources_source_key UNIQUE (source);


--
-- Name: draft_bullets draft_bullets_bullets_id_fk; Type: FK CONSTRAINT; Schema: bullets; Owner: -
--

ALTER TABLE ONLY bullets.draft_bullets
    ADD CONSTRAINT draft_bullets_bullets_id_fk FOREIGN KEY (bullet_id) REFERENCES bullets.bullets(id);


--
-- Name: draft_bullets draft_bullets_draft_id_fk; Type: FK CONSTRAINT; Schema: bullets; Owner: -
--

ALTER TABLE ONLY bullets.draft_bullets
    ADD CONSTRAINT draft_bullets_draft_id_fk FOREIGN KEY (draft_id) REFERENCES news.draft(id);


--
-- Name: news_entities news_entities_entities_id_fk; Type: FK CONSTRAINT; Schema: entities; Owner: -
--

ALTER TABLE ONLY entities.news_entities
    ADD CONSTRAINT news_entities_entities_id_fk FOREIGN KEY (entity_id) REFERENCES entities.entities(id);


--
-- Name: news_entities news_entities_news_id_fk; Type: FK CONSTRAINT; Schema: entities; Owner: -
--

ALTER TABLE ONLY entities.news_entities
    ADD CONSTRAINT news_entities_news_id_fk FOREIGN KEY (news_id) REFERENCES news.news(id);


--
-- Name: news news_dedup_groups_id_fk; Type: FK CONSTRAINT; Schema: news; Owner: -
--

ALTER TABLE ONLY news.news
    ADD CONSTRAINT news_dedup_groups_id_fk FOREIGN KEY (dedup_group_id) REFERENCES news.dedup_groups(id);


--
-- Name: news news_draft_id_fk; Type: FK CONSTRAINT; Schema: news; Owner: -
--

ALTER TABLE ONLY news.news
    ADD CONSTRAINT news_draft_id_fk FOREIGN KEY (draft_id) REFERENCES news.draft(id);


--
-- Name: news_sources news_sources_news_id_fk; Type: FK CONSTRAINT; Schema: sources; Owner: -
--

ALTER TABLE ONLY sources.news_sources
    ADD CONSTRAINT news_sources_news_id_fk FOREIGN KEY (news_id) REFERENCES news.news(id);


--
-- Name: news_sources news_sources_sources_id_fk; Type: FK CONSTRAINT; Schema: sources; Owner: -
--

ALTER TABLE ONLY sources.news_sources
    ADD CONSTRAINT news_sources_sources_id_fk FOREIGN KEY (source_id) REFERENCES sources.sources(id);


--
-- PostgreSQL database dump complete
--

